### ISSUE TITLE
ERROR F7 NOT WORKING

### ISSUE THREAD

**Issue by fonmach** [oldnapalm/MapEditor#12]
[11:31:13] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[11:31:13] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[11:31:13] [DEBUG] Loading scripts from C:\Program Files\Rockstar Games\Grand Theft Auto V\scripts ...
[11:31:13] [DEBUG] Loading assembly ClearScript.dll ...
[11:31:13] [INFO] Found 0 script(s) in ClearScript.dll.
[11:31:13] [DEBUG] Loading assembly MapEditor.dll ...
[11:31:13] [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.
[11:31:13] [DEBUG] Loading assembly NativeUI.dll ...
[11:31:13] [INFO] Found 1 script(s) in NativeUI.dll resolved to API 2.11.6.
[11:31:13] [DEBUG] Instantiating script MapEditor.JavascriptHook ...
[11:31:13] [INFO] Started script MapEditor.JavascriptHook.
[11:31:13] [DEBUG] Instantiating script MapEditor.MapEditor ...
[11:31:14] [ERROR] Failed to instantiate script MapEditor.MapEditor because constructor threw an exception: System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.StringToCoTaskMemUTF8(String s)
   at SHVDN.ScriptDomain.PinString(String str)
   at GTA.Native.Function.ObjectToNative(Object value)
   at GTA.World.AddRelationshipGroup(String groupName)
   at MapEditor.ObjectDatabase.SetupRelationships()
   at MapEditor.MapEditor..ctor()
[11:31:14] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[11:31:14] [INFO] Started script NativeUI.BigMessageThread.

**Comment by oldnapalm** [comment]
This is a SHVDN incompatibility issue with the last game update, please see #11.

Closing as duplicate.
